Redirecting all logs to /var/log/ovirt.log

diff --git a/ovirt-managed-node/src/scripts/ovirt b/ovirt-managed-node/src/scripts/ovirt
--- a/ovirt-managed-node/src/scripts/ovirt
+++ b/ovirt-managed-node/src/scripts/ovirt
@@ -11,15 +11,14 @@
 . /etc/init.d/ovirt-functions
 
 start() {
-    echo -n $"Starting ovirt: "
-
     find_srv ipa tcp
     krb5_conf=/etc/krb5.conf
     if [ ! -s $krb5_conf ]; then
         rm -f $krb5_conf
         # FIXME this is IPA specific
-        wget -q http://$SRV_HOST:$SRV_PORT/ipa/config/krb5.ini -O $krb5_conf \
-            || die "Failed to get $krb5_conf"
+        wget -q \
+            http://$SRV_HOST:$SRV_PORT/ipa/config/krb5.ini -O $krb5_conf \
+            || echo "Failed to get $krb5_conf" && return 1
     fi
     IPA_HOST=$SRV_HOST
     IPA_PORT=$SRV_PORT
@@ -34,16 +33,20 @@ start() {
         sed -e "s/@COLLECTD_SERVER@/$SRV_HOST/" \
             -e "s/@COLLECTD_PORT@/$SRV_PORT/" $collectd_conf.in \
             > $collectd_conf \
-            || die "Failed to write $collectd_conf"
+            || echo "Failed to write $collectd_conf" && return 1
     fi
-
-    success
-    echo
 }
 
 case "$1" in
     start)
-        start
+        echo -n $"Starting ovirt: "
+
+        {
+            start
+        } >> $OVIRT_LOGFILE 2>&1
+
+        test $? == 0 && success || failure
+        echo
         ;;
     *)
         echo "Usage: ovirt {start}"
