wait for db to become ready
wait until we can connect to the database or timeout occurs

Signed-off-by: Alan Pevec <apevec@redhat.com>

diff --git a/wui/scripts/ovirt-wui-install b/wui/scripts/ovirt-wui-install
--- a/wui/scripts/ovirt-wui-install
+++ b/wui/scripts/ovirt-wui-install
@@ -135,6 +135,21 @@ echo "host all all 127.0.0.1 255.255.255.0 trust" >> /var/lib/pgsql/data/pg_hba.
 service postgresql stop > /dev/null 2>&1
 service postgresql start
 [ $? != 0 ] && echo "Failed to start database" && exit 1
+declare -i timeout=10
+while [[ timeout -gt 0 ]]
+do
+  psql -l -U postgres > /dev/null 2>&1
+  rc=$?
+  if [[ rc -eq 0 ]]
+  then
+     break
+  else
+     echo Database not ready yet, retrying...
+  fi
+  let timeout--
+  sleep 2
+done
+[[ timeout -eq 0 ]] && echo "Failed to start database" && exit 1
 
 if [ -z $PASSWD ]; then
     # generate random pg user password
