Missing /dev/mapper entries for partitions
Unclear what removes /dev/mapper/*p*, mappings are shown with dmsetup ls
so devmapper still "sees" the partition entries.
By simply issuing dmsetup mknodes, the device nodes for partitions get
restored under /dev/mapper/

From: rmm@br.ibm.com
Signed-off-by: Alan Pevec <apevec@redhat.com>

diff --git a/scripts/ovirt-config-boot b/scripts/ovirt-config-boot
--- a/scripts/ovirt-config-boot
+++ b/scripts/ovirt-config-boot
@@ -82,6 +82,11 @@ ovirt_boot_setup() {
     local oldtitle
     if [ "$OVIRT_ISCSI_ENABLED" != "y" ]; then
         # get title for the current Root
+        /sbin/dmsetup mknodes
+        if [ $? -ne 0 ] ; then
+          log "Could not create DM links"
+          return 1
+        fi
         mount -r LABEL=Root /liveos
         mountpoint /liveos > /dev/null
         if [ $? -ne 0 ] ; then
