Fix autoinstall to stop if any step fails for debugging
Autoinstall would blindly try to run every step even if a previous
step failed.  Changed to stop running if one fails.  Also, don't
reboot if any step fails.

rhbz#613754

diff --git a/scripts/ovirt-firstboot b/scripts/ovirt-firstboot
--- a/scripts/ovirt-firstboot
+++ b/scripts/ovirt-firstboot
@@ -40,14 +40,28 @@ start_ovirt_firstboot ()
     fi
 
     touch $VAR_SUBSYS_OVIRT_FIRSTBOOT
+    /sbin/restorecon -e /var/lib/stateless/writable -e /data -e /config -e /proc -e /sys -rv / >> $OVIRT_TMP_LOGFILE 2>&1
 
     if is_auto_install; then
-        /usr/libexec/ovirt-config-storage AUTO
-        /usr/libexec/ovirt-config-hostname AUTO
-        /usr/libexec/ovirt-config-networking AUTO
-        /usr/libexec/ovirt-config-logging AUTO
-        /usr/libexec/ovirt-config-password AUTO
-        /usr/libexec/ovirt-config-snmp AUTO
+        /usr/libexec/ovirt-config-storage AUTO && \
+        /usr/libexec/ovirt-config-hostname AUTO && \
+        /usr/libexec/ovirt-config-networking AUTO && \
+        /usr/libexec/ovirt-config-logging AUTO && \
+        /usr/libexec/ovirt-config-password AUTO && \
+        /usr/libexec/ovirt-config-snmp AUTO && \
+        /usr/libexec/ovirt-config-rhn AUTO
+        rc=$?
+        # Handle Log file
+        if [ -f $OVIRT_TMP_LOGFILE ]; then
+            cat $OVIRT_TMP_LOGFILE >> $OVIRT_LOGFILE
+            rm -f $OVIRT_TMP_LOGFILE
+        fi
+        if [ $rc -ne 0 ]; then
+            log "Automatic installation failed. Please review console messages."
+            log "Press Enter to drop to emergency shell."
+            read < /dev/console
+            bash < /dev/console
+        fi
     fi
 
     if is_upgrade; then
