provide a log out method from setup for ssh/console
rhbz#741942

Signed-off-by: Joey Boggs <jboggs@redhat.com>

diff --git a/scripts/ovirt-admin-shell b/scripts/ovirt-admin-shell
--- a/scripts/ovirt-admin-shell
+++ b/scripts/ovirt-admin-shell
@@ -9,3 +9,10 @@ if [[ $TTY =~ "pts" ]]; then
     sudo rm -rf /tmp/ovirt-setup.$TTY
 fi
 sudo /usr/libexec/ovirt-config-setup
+
+# check for logout return code and drop to login prompt
+ret=$?
+if [[ $ret == 2 ]]; then
+    sudo rm -rf /tmp/ovirt-setup.$TTY
+    /usr/bin/clear; exit
+fi
