handle spaces in device names, follow-up
- add more missing quotes
- flush cache to sync DM and blockdev, workaround from rhbz#623846#c14
- use blkid -c /dev/null instead of findfs

rhbz#613754

diff --git a/scripts/ovirt-config-boot b/scripts/ovirt-config-boot
--- a/scripts/ovirt-config-boot
+++ b/scripts/ovirt-config-boot
@@ -60,17 +60,11 @@ ovirt_boot_setup() {
       return 1
     fi
 
-    local found_boot=false
-    if findfs LABEL=Boot >/dev/null 2>&1 ; then
-        found_boot=true
-        grub_dev_label=Boot
-    elif findfs LABEL=Root >/dev/null 2>&1 ; then
-        found_boot=false
-        grub_dev_label=Root
-    fi
-    if $found_boot; then
-        mount_boot
-        mountpoint /boot
+    grub_dev="$(findfs LABEL=Boot 2>&1)"
+    if [ $? -eq 0 ]; then
+        # minimal boot partition for iscsi root
+        mount "$grub_dev" /boot
+        mountpoint /boot > /dev/null
         if [ $? -ne 0 ] ; then
             log "Boot partition not available"
             return 1
@@ -79,75 +73,73 @@ ovirt_boot_setup() {
         # file created only if OVIRT_ISCSI_ENABLED=y
         if [ -f /boot/ovirt ]; then
             . /boot/ovirt
-        iscsiadm -p $OVIRT_ISCSI_TARGET_IP:$OVIRT_ISCSI_TARGET_PORT -m discovery -t sendtargets
-        log "Restarting iscsi service"
-        service iscsi restart
+            iscsiadm -p $OVIRT_ISCSI_TARGET_IP:$OVIRT_ISCSI_TARGET_PORT -m discovery -t sendtargets
+            log "Restarting iscsi service"
+            service iscsi restart
         fi
-    else
-        grub_dev_label="RootBackup"
-    fi
-
-    # check that /boot mounted ok and find partition number for GRUB, $4 is to allow 0 as a partition number for grub
-    get_part_info "$(readlink -f "$(findfs LABEL=$grub_dev_label 2>/dev/null)")" disk partN y
-    rc=$?
-    if [ $rc -ne 0 -o "$partN" -lt 0 ]; then
-      log "unable to determine Root partition"
-      return 1
     fi
 
     local oldtitle
     if [ "$OVIRT_ISCSI_ENABLED" != "y" ]; then
-        mount_liveos
-        mountpoint /liveos
+        # get title for the current Root
+        mount -r LABEL=Root /liveos
+        mountpoint /liveos > /dev/null
         if [ $? -ne 0 ] ; then
           log "Root partition not available"
           return 1
         fi
 
         initrd_dest="/liveos"
-        grub_dir="/liveos/boot/grub"
-        grub_prefix="/boot/grub"
+        grub_dir="/liveos/grub"
+        grub_prefix="/grub"
 
         if [ -e "$initrd_dest/vmlinuz0" -a -e "$initrd_dest/initrd0.img" ]; then
             oldtitle="BACKUP $(grep ^title ${grub_dir}/grub.conf|head -n1|cut -c7-)"
         fi
+        umount /liveos
 
         # prepare Root partition update
-        candidate=
-        if findfs LABEL=RootBackup >/dev/null 2>&1 ; then
-            candidate=RootBackup
-        elif findfs LABEL=RootUpdate >/dev/null 2>&1 ; then
-            candidate=RootUpdate
-        elif findfs LABEL=RootNew >/dev/null 2>&1 ; then
-            candidate=RootNew
-        fi
-        if [ -z "$candidate" ]; then
-            rc=1
-        elif [ "$candidate" = "RootNew" ]; then
-            umount /liveos
-            candidate_dev="$(findfs LABEL=$candidate 2>/dev/null)"
-            rc=$?
-        else
-            candidate_dev="$(findfs LABEL=$candidate 2>/dev/null)"
+        rc=1
+        candidate_dev="$(findfs LABEL=RootBackup 2>/dev/null)"
+        if [ $? -eq 0 ]; then
             e2label "$candidate_dev" RootNew
             rc=$?
+        else
+            candidate_dev="$(findfs LABEL=RootUpdate 2>/dev/null)"
+            if [ $? -eq 0 ]; then
+                e2label "$candidate_dev" RootNew
+                rc=$?
+            else
+                candidate_dev="$(findfs LABEL=RootNew 2>/dev/null)"
+                rc=$?
+                umount /liveos ||:
+            fi
         fi
         if [ $rc -ne 0 ]; then
-          log "root partition not available."
-          log "$(ls -al /dev/disk/by-label)"
-          return $rc
+            log "root partition not available."
+            log "$(ls -al /dev/disk/by-label)"
+            return $rc
         fi
 
-        mount "$candidate_dev" /liveos/
+        mount "$candidate_dev" /liveos
 
         rm -rf /liveos/LiveOS
         mkdir -p /liveos/LiveOS
+        grub_dev="$candidate_dev"
 
     else
         initrd_dest="/boot"
         grub_dir="/boot/grub"
         grub_prefix="/grub"
         oldtitle=
+    fi
+
+    # find partition number for GRUB, $4 is to allow 0 as a partition number for grub
+    get_part_info "$(readlink -f "$grub_dev")" disk partN y
+    rc=$?
+    if [ $rc -ne 0 -o "$partN" -lt 0 ]; then
+      log "unable to determine Root partition"
+      return 1
     fi
 
 
@@ -163,19 +155,19 @@ ovirt_boot_setup() {
         cp -p $live/LiveOS/squashfs.img /liveos/LiveOS
         rc=$?
         if [ $rc -ne 0 ]; then
-          log "squashfs image copy failed."
-          return $rc
+            log "squashfs image copy failed."
+            return $rc
         fi
     fi
 
     # reorder tty0 to allow both serial and phys console after installation
     if [ "$OVIRT_ISCSI_ENABLED" = "y" ]; then
         root_part="root=LABEL=ovirt-node-root"
-        bootparams="ro roottypefs=ext4 console=tty0 \
+        bootparams="ro roottypefs=ext2 console=tty0 \
                     netroot=iscsi:$OVIRT_ISCSI_TARGET_IP::$OVIRT_ISCSI_TARGET_PORT::$OVIRT_ISCSI_NODE_NAME ip=eth0:dhcp"
     else
         root_part="root=live:LABEL=Root"
-        bootparams="ro roottypefs=ext4 console=tty0 \
+        bootparams="ro roottypefs=ext2 console=tty0 \
                 $(echo $bootparams | sed s/console=tty0//g)"
     fi
     mkdir -p $grub_dir
@@ -209,6 +201,9 @@ EOF
         disk2=$(multipath -l "$disk" | awk '/ active / {print $3}')
         if [ -n "$disk2" ]; then
             disk="/dev/$disk2"
+            # flush to sync DM and blockdev, workaround from rhbz#623846#c14
+            echo 3 > /proc/sys/vm/drop_caches
+            partprobe "$disk"
         fi
     fi
     echo "(hd0) $disk" > $grub_dir/device.map
@@ -235,10 +230,12 @@ EOF
         # mark new Root ready to go, reboot() in ovirt-function switches it to active
         e2label "$candidate_dev" RootUpdate
         mount "$candidate_dev" /liveos
+        ln -snf /liveos/grub /boot/grub
         grub <<EOF_SAVEDEFAULT
 savedefault --default=$backup_entry
 savedefault --default=0 --once
 EOF_SAVEDEFAULT
+        umount /liveos
     fi
 
     if [ "$OVIRT_ISCSI_ENABLED" = "y" ]; then
diff --git a/scripts/ovirt-config-uninstall b/scripts/ovirt-config-uninstall
--- a/scripts/ovirt-config-uninstall
+++ b/scripts/ovirt-config-uninstall
@@ -46,38 +46,35 @@ if ask_yes_or_no "Do you wish to continue and uninstall this node ([Y]es/[N]o)?"
         elif findfs LABEL=RootNew 2>&1 >/dev/null; then
             root2=RootNew
         fi
-        if ! get_part_info $(findfs LABEL=Root 2>/dev/null) root_dev root_part; then
-            log "Can't find Root device"
-            exit 2
-        fi
-        if ! get_part_info $(findfs LABEL=${root2} 2>/dev/null) root2_dev root2_part; then
-            log "Can't find RootBackup/RootNew/RootUpdate device"
-            exit 3
-        fi
-        if ! get_part_info $(pvs --noheadings -o pv_name,vg_name | grep HostVG | awk '{print $1}') pv_dev pv_part; then
-            log "Can't find HostVG device"
-            exit 4
-        fi
+        get_part_info "$(pvs --noheadings -o pv_name,vg_name | grep HostVG | sed -e 's/ HostVG$//' -e 's/^ *//')" pv_dev pv_part
         log "Removing volume group"
-        wipe_volume_group "HostVG"
+        wipe_volume_group HostVG
+        if [ -n "$pv_dev" -a -n "$pv_part" ]; then
+            pvremove "$pv_dev$pv_part"
+            parted -s "$pv_dev" "rm $pv_part"
+        fi
         log "Removing partitions"
-        parted -s $root_dev "rm $root_part"
-        pvremove ${vg_dev}
-        parted -s $root2_dev "rm $root2_part"
-        parted -s $vg_dev "rm $vg_part"
-        wipe_partitions $pv_dev
-        wipe_partitions $root_dev
-        wipe_partitions $root2_dev
+        get_part_info "$(findfs LABEL=Root 2>/dev/null)" root_dev root_part
+        if [ -n "$root_dev" -a -n "$root_part" ]; then
+            parted -s "$root_dev" "rm $root_part"
+        fi
+        get_part_info "$(findfs LABEL=${root2}" 2>/dev/null) root2_dev root2_part
+        if [ -n "$root2_dev" -a -n "$root2_part" ]; then
+            parted -s "$root2_dev" "rm $root2_part"
+        fi
+        wipe_partitions "$pv_dev"
+        wipe_partitions "$root_dev"
+        wipe_partitions "$root2_dev"
         #restart multipath
         multipath -F
         multipath -v3
         service multipathd start 6>&- 7>&-
-	    log "Finished uninstalling node."
+        log "Finished uninstalling node."
         stop_log
     else
-	    log "There is no installed node instance to remove."
-	    log "Aborting"
-	    exit 1
+        log "There is no installed node instance to remove."
+        log "Aborting"
+        exit 1
     fi
 else
     log "Aborted"
