Don't continue if auto-install encounters an error
Autoinstall should not try to reboot if something fails during
installation.  This patch fixes 3 areas that weren't covered before.

- relabeling partitions
- installation of the image
- hooks failure

rhbz#681938

diff --git a/scripts/ovirt-firstboot b/scripts/ovirt-firstboot
--- a/scripts/ovirt-firstboot
+++ b/scripts/ovirt-firstboot
@@ -33,6 +33,15 @@ VAR_SUBSYS_OVIRT_FIRSTBOOT=/var/lock/subsys/$prog
 trap '__st=$?; stop_log; exit $__st' 0
 trap 'exit $?' 1 2 13 15
 
+autoinstall_failed(){
+    if is_auto_install; then
+        log "Automatic installation failed. Please review console messages."
+        log "Press Enter to drop to emergency shell."
+        read < /dev/console
+        bash < /dev/console
+    fi
+}
+
 start_ovirt_firstboot ()
 {
     if ! is_firstboot && ! is_auto_install && ! is_upgrade; then
@@ -61,20 +70,23 @@ start_ovirt_firstboot ()
             rm -f $OVIRT_TMP_LOGFILE
         fi
         if [ $rc -ne 0 ]; then
-            log "Automatic installation failed. Please review console messages."
-            log "Press Enter to drop to emergency shell."
-            read < /dev/console
-            bash < /dev/console
+            autoinstall_failed
         fi
     fi
 
     if is_upgrade; then
         mount_live
         /usr/libexec/ovirt-config-boot /live "$OVIRT_BOOTPARAMS" no
+        if [ $? -ne 0 ]; then
+            autoinstall_failed
+        fi
         disable_firstboot
         ovirt_store_firstboot_config
         reboot
-        return
+        if [ $? -ne 0 ]; then
+            autoinstall_failed
+        fi
+        return 1
     fi
 
     if is_firstboot; then
diff --git a/scripts/ovirt-functions b/scripts/ovirt-functions
--- a/scripts/ovirt-functions
+++ b/scripts/ovirt-functions
@@ -864,16 +864,21 @@ findfs() {
 #   cleanup before reboot
 reboot() {
     cd /
+    rc=0
     if [ "$OVIRT_ISCSI_ENABLED" != "y" ]; then
         # setup new Root if update is prepared
         root_update_dev="$(findfs LABEL=RootUpdate 2>/dev/null)"
         if [ -n "$root_update_dev" ]; then
             set -x
             root_dev="$(findfs LABEL=Root 2>/dev/null)"
-            e2label "$root_dev" RootBackup
-            e2label "$root_update_dev" Root
+            e2label "$root_dev" RootBackup || rc=1
+            e2label "$root_update_dev" Root || rc=1
             set +x
         fi
+    fi
+    if [ $rc -ne 0 ]; then
+        log "Relabeling failed, please check logs"
+        return 1
     fi
     # run post-install hooks
     # e.g. to avoid reboot loops using Cobbler PXE only once
@@ -882,6 +887,10 @@ reboot() {
     #   -O /dev/null
     for hook in $(ls /etc/ovirt-config-boot.d/* 2>/dev/null); do
         $hook
+        rc=$?
+        if [ $? -ne 0 ]; then
+            log "Hook \"$hook\" failed."
+        fi
     done
     /sbin/reboot
 }
