Makes the managed node boot up process more generic.
Refactored the sysvinit scripts so that developers can insert their own
startup code into the boot process.

Added a new system configuration file, /etc/sysconfig/node-config.

Added /etc/node.d/ to allow developers to add scripts to be executed
during the startup process.

diff --git a/scripts/ovirt-awake b/scripts/ovirt-awake
--- a/scripts/ovirt-awake
+++ b/scripts/ovirt-awake
@@ -1,9 +1,8 @@
 #!/bin/bash
 #
-# ovirt-awake   Notifies the oVirt server that an oVirt Node is
-#               starting up.
+# ovirt-awake - Notifies any management server that the node is starting.
 #
-# Copyright (C) 2008 Red Hat, Inc.
+# Copyright (C) 2008-2010 Red Hat, Inc.
 # Written by Darryl L. Pierce <dpierce@redhat.com>
 #
 # This program is free software; you can redistribute it and/or modify
@@ -20,86 +19,135 @@
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 # MA  02110-1301, USA.  A copy of the GNU General Public License is
 # also available at http://www.gnu.org/copyleft/gpl.html.
+#
+### BEGIN INIT INFO
+# Provides: ovirt-awake
+# Default-Start: 2 3 4 5
+# Description: Managed node service to alert management servers.
+### END INIT INFO
 
-# Source function library
+# Source functions library
+# config: /etc/sysconfig/node-config
+
 . /etc/init.d/functions
 . /etc/init.d/ovirt-functions
 
-function connect-to-server () {
-    echo "Connecting to $SRV_HOST:$SRV_PORT"
-    exec 3<> /dev/tcp/$SRV_HOST/$SRV_PORT
+prog=ovirt-early
+NODE_CONFIG=/etc/sysconfig/node-config
+VAR_SUBSYS_NODECONFIG=/var/lock/subsys/node-config
+
+# load the configuration file
+[ -f "$NODE_CONFIG" ] && . "$NODE_CONFIG"
+
+send_text () {
+    local text=${1}
+
+    echo "$text" 1>&3
 }
 
-function disconnect-from-server () {
-    <&3-
-}
-
-function send-text () {
-    echo "$1" 1>&3
-}
-
-function receive-text () {
+receive_text () {
     read 0<&3
 }
 
-function error () {
-  errmsg="ERR: (ovirt-awake) $1"
-  send-text "$errmsg"
-  log "$errmsg"
+error () {
+    local text=${1-}
+
+    send_text "ERR: (ovirt-awake) ${text}"
+    # log "${text}"
 }
 
-start () {
-    connect-to-server
+ovirt_startup () {
+    local mgmthost=${OVIRT_MANAGEMENT_SERVER}
+    local mgmtport=${OVIRT_MANAGEMENT_PORT}
 
-    receive-text
-
-    if [ $REPLY == "HELLO?" ]; then
-        echo "Starting wakeup conversation."
-
-        send-text "HELLO!"
-
-        read 0<&3
-
-        if [ $REPLY == "MODE?" ]; then
-            send-text "AWAKEN"
-
-            receive-text
-
-            KEYTAB=`echo $REPLY | awk '{ print $2 }'`
-
-            if [ -n "$KEYTAB" -a -n "$KEYTAB_FILE" ]; then
-                echo "Retrieving keytab: '$KEYTAB'"
-
-                wget -q "$KEYTAB" --no-check-certificate --output-document="$KEYTAB_FILE"
-            else
-                echo "No keytab to retrieve"
-            fi
-            send-text ACK
-        else
-            error "Did not get a mode request."
-        fi
-    else
-        error "Did not get a proper startup marker."
+    if [[ -z "${mgmthost}" ]] || [[ -z "${mgmtport}" ]]; then
+        find_srv identify tcp
+        mgmthost=$SRV_HOST
+        mgmtport=$SRV_PORT
     fi
 
-    echo "Disconnecting."
+    if [[ -n "${mgmthost}" ]] && [[ -n "${mgmtport}" ]]; then
+        # log "Notifying oVirt management server: ${mgmthost}:${mgmtport}"
+        exec 3<> /dev/tcp/$mgmthost:$mgmtport
 
-    disconnect-from-server
+        connect-to-server
+        receive_text
+        if [ $REPLY == "HELLO?" ]; then
+            logo "Starting wakeup conversation."
+            send_text "HELLO!"
+            receive_text
+            if [ $REPLY == "MODE?" ]; then
+                send_text "AWAKEN"
+                receive_text
+                KEYTAB=$(echo $REPLY | awk '{ print $2 }')
+                if [ -n "$KEYTAB" -a -n "$KEYTAB_FILE" ]; then
+                    # log "Retrieving keytab: '$KEYTAB'"
+                    wget -q "$KEYTAB" --no-check-certificate --output-document="$KEYTAB_FILE"
+                else
+                    log "No keytab to retrieve"
+                fi
+                send_text ACK
+            else
+                error "Did not get a mode request."
+            fi
+        else
+            error "Did not get a proper startup marker."
+        fi
+        # log "Disconnecting."
+        <&3-
+    else
+        # log "Missing server information. Failing..."
+        return 1
+    fi
+}
+
+# Override this method to provide support for notifying a management
+# system that the node has started and will be available after
+# system initialization
+start () {
+    local RC=0
+
+    touch $VAR_SUBSYS_NODECONFIG
+    # log "Starting ovirt-awake."
+    case "$OVIRT_RUNTIME_MODE" in
+        "none")
+            log "Node is operating in unmanaged mode."
+            ;;
+        "ovirt")
+            ovirt_startup
+            RC=$?
+            ;;
+        "managed")
+            if [ -x /config/$MANAGEMENT_SCRIPTS_DIR/awake ]; then
+                log "Executing /config/$MANAGEMENT_SCRIPTS_DIR/awake"
+                /config/$MANAGEMENT_SCRIPTS_DIR/awake
+            else
+                echo "No script found to notify management server during awake state."
+            fi
+            ;;
+    esac
+
+    # log "Completed ovirt-awake: RC=${RC}"
+    rm -f $VAR_SUBSYS_NODECONFIG
+    return $RC
 }
 
 case "$1" in
     start)
-        SRV_HOST=$2
-        SRV_PORT=$3
-        KEYTAB_FILE=$4
-        start
-        RETVAL=$?
-    ;;
+        echo -n "Starting ovirt-awake: "
+        [ -f "$VAR_SUBSYS_NODECONFIG" ] && exit 0
+        {
+            start
+            RETVAL=$?
+            log "Completed ovirt-awake: RETVAL=$?"
+        } >> $OVIRT_LOGFILE 2>&1
+        test $RETVAL == 0 && success || failure
+        ;;
 
     *)
         echo "Usage: $0 start"
         RETVAL=2
-    ;;
+        ;;
 esac
 
 exit $RETVAL
diff --git a/scripts/ovirt-early b/scripts/ovirt-early
--- a/scripts/ovirt-early
+++ b/scripts/ovirt-early
@@ -2,16 +2,22 @@
 #
 # ovirt-early Start early ovirt services
 #
-# chkconfig: - 01 99
-# description: ovirt-early services
-#
+### BEGIN INIT INFO
+# Provides: ovirt-early
+# Required-Start: ovirt-awake
+# Default-Start: 2 3 4 5
+# Dewscription: Managed node early configuration service
+### END INIT INFO
 
 # Source functions library
 . /etc/init.d/functions
 . /etc/init.d/ovirt-functions
 
 prog=ovirt-early
-lockfile=/var/lock/subsys/$prog
+VAR_SUBSYS_OVIRT_EARLY=/var/lock/subsys/$prog
+
+# load the configuration file
+[ -f "$NODE_CONFIG" ] && . "$NODE_CONFIG"
 
 BONDING_MODCONF_FILE=/etc/modprobe.d/bonding
 AUGTOOL_CONFIG=/var/tmp/augtool-config
@@ -23,16 +29,16 @@ get_mac_addresses() {
     macs=""
     devices=$(ls -b /sys/class/net/)
     for device in $devices; do
-	if [ "$device" != "$DEVICE" ]; then
-	    mac=$(cat /sys/class/net/$device/address 2>/dev/null)
-	    if [ -n "$mac" -a "$mac" != "00:00:00:00:00:00" ]; then
-		macs="${macs}${mac}=${device},"
-	    fi
-	fi
+        if [ "$device" != "$DEVICE" ]; then
+            mac=$(cat /sys/class/net/$device/address 2>/dev/null)
+            if [ -n "$mac" -a "$mac" != "00:00:00:00:00:00" ]; then
+                macs="${macs}${mac}=${device},"
+            fi
+        fi
     done
 }
 
-configure_from_network() {
+configure_ovirt_management_nic() {
     DEVICE=$1
 
     if [ -n "$DEVICE" ]; then
@@ -62,12 +68,12 @@ configure_from_network() {
                     if [ $? -eq 0 ]; then
                         log "Remote configuration bundle retrieved to $cfgdb"
                         ovirt-process-config $cfgdb $BONDING_MODCONF_FILE $AUGTOOL_CONFIG
-			if [ $? -eq 0 ]; then
-			    log "Remote configuration retrieved and applied"
+                        if [ $? -eq 0 ]; then
+                            log "Remote configuration retrieved and applied"
                             rm $cfgdb
-			else
-			    log "Failure to retrieve or apply remote configuration"
-			fi
+                        else
+                            log "Failure to retrieve or apply remote configuration"
+                        fi
                     else
                         log "Failed to retrieve configuration bundle"
                     fi
@@ -88,11 +94,11 @@ configure_from_network() {
     if [ ! -f $ifcfg ]; then
         log "Applying default configuration to $DEVICE and $BRIDGE"
         printf '%s\n' "DEVICE=$DEVICE" ONBOOT=yes "BRIDGE=$BRIDGE" \
-	    > /etc/sysconfig/network-scripts/ifcfg-$DEVICE
+            > /etc/sysconfig/network-scripts/ifcfg-$DEVICE
         printf '%s\n' "DEVICE=$BRIDGE" "BOOTPROTO=dhcp" \
-	    ONBOOT=yes TYPE=Bridge PEERNTP=yes DELAY=0 \
-	    > /etc/sysconfig/network-scripts/ifcfg-$BRIDGE
-	log "Default config applied"
+            ONBOOT=yes TYPE=Bridge PEERNTP=yes DELAY=0 \
+            > /etc/sysconfig/network-scripts/ifcfg-$BRIDGE
+        log "Default config applied"
     fi
 }
 
@@ -135,9 +141,39 @@ find_disk() {
     return 1
 }
 
+configure_management_interface() {
+    log "Configuring the manangement interface."
+    case $OVIRT_RUNTIME_MODE in
+        "ovirt")
+            configure_ovirt_management_nic $bootif
+            if [ -n "$init" ]; then
+                ovirt-config-storage AUTO
+                # initial configuration storage, after /config creation
+                ovirt_store_config \
+                    /etc/sysconfig/network-scripts/ifcfg-* \
+                    $BONDING_MODCONF_FILE
+                if [ $upgrade = 1 ]; then
+                    # local disk installation for managed mode
+                    mount_live
+                    ovirt-config-boot /live "$bootparams"
+                fi
+            fi
+            ;;
+        "managed")
+            if [ -x $MANAGEMENT_SCRIPTS_DIR/configure-management-interface ]; then
+                log "Executing $MANAGEMENT_SCRIPTS_DIR/configure-management-interface"
+                $MANAGEMENT_SCRIPTS_DIR/configure-management-interface
+            else
+                echo "No script to configure management interface found."
+            fi
+            ;;
+        "none")
+            log "Unmanaged node: no management interface to configure."
+    esac
+}
 
 start() {
-    touch $lockfile
+    touch $VAR_SUBSYS_OVIRT_EARLY
     # oVirt boot parameters
     #   BOOTIF=link|eth*|<MAC> (appended by pxelinux)
     #   ovirt_init=[usb|scsi[:serial#]|/dev/...]
@@ -351,21 +387,21 @@ start() {
             dns=*)
             dns=${i#dns=}
             ;;
-	    ntp=*)
-	    ntp=${i#ntp=}
-	    ;;
+            ntp=*)
+            ntp=${i#ntp=}
+            ;;
             hostname=*)
             hostname=${i#hostname=}
             ;;
             vlan=*)
             vlan=${i#vlan=}
             ;;
-	    ssh_pwauth=1 | ssh_pwauth=true)
-	    ssh_pwauth=true
-	    ;;
-	    ssh_pwauth=0 | ssh_pwauth=false)
-	    ssh_pwauth=false
-	    ;;
+            ssh_pwauth=1 | ssh_pwauth=true)
+            ssh_pwauth=true
+            ;;
+            ssh_pwauth=0 | ssh_pwauth=false)
+            ssh_pwauth=false
+            ;;
             syslog=*)
             i=${i#syslog=}
             eval $(printf $i|awk -F: '{print "syslog_server="$1; print "syslog_port="$2;}')
@@ -438,22 +474,10 @@ start() {
             -e "s/^mech_list: .*gssapi.*/mech_list: digest-md5/" \
             /etc/sasl2/libvirt.conf
     else
-        configure_from_network $bootif
-        if [ -n "$init" ]; then
-            ovirt-config-storage AUTO
-            # initial configuration storage, after /config creation
-            ovirt_store_config \
-                /etc/sysconfig/network-scripts/ifcfg-* \
-                $BONDING_MODCONF_FILE
-            if [ $upgrade = 1 ]; then
-                # local disk installation for managed mode
-                mount_live
-                ovirt-config-boot /live "$bootparams"
-            fi
-        fi
+        configure_manament_interface
     fi
 
-    rm -f $lockfile
+    rm -f $VAR_SUBSYS_OVIRT_EARLY
 
     for hook in $ovirt_early; do
         post="$EARLY_DIR/post-$hook"
@@ -465,49 +489,22 @@ start() {
     return 0
 }
 
-scan_for_swap() {
-    # swap partition activation
-    # find all of the partitions on the system
-
-    # get the system pagesize
-    PAGESIZE=`getconf PAGESIZE`
-
-    # look first at raw partitions XXX disk/by-id or HAL? (for cciss)
-    BLOCKDEVS=`ls /dev/sd? /dev/hd? 2>/dev/null`
-
-    # now LVM partitions
-    LVMDEVS="$DEVICES `lvscan | awk '{print $2}' | tr -d \"'\"`"
-
-    SWAPDEVS="$LVMDEVS"
-    for dev in $BLOCKDEVS; do
-        SWAPDEVS="$SWAPDEVS `fdisk -l $dev 2>/dev/null | tr '*' ' ' \
-                                     | awk '$5 ~ /82/ {print $1}'`"
-    done
-
-    # now check if any of these partitions are swap, and activate if so
-    for device in $SWAPDEVS; do
-        sig=`dd if=$device bs=1 count=10 skip=$(( $PAGESIZE - 10 )) \
-            2>/dev/null`
-        if [ "$sig" = "SWAPSPACE2" ]; then
-            swapon $device
-        fi
-    done
+stop() {
+    echo -n "Stopping ovirt-early: "
+    success
 }
 
 case "$1" in
     start)
-        printf "Starting ovirt-early: "
-
+        [ -f "$VAR_SUBSYS_NODE_CONFIG" ] && exit 0
+        echo -n "Starting ovirt-early: "
         {
-            start_log
             log "Starting ovirt-early"
             start
             log "Completed ovirt-early"
-            stop_log
-        }
-
-        test $? == 0 && success || failure
-        echo
+            RETVAL=$?
+        } >> $OVIRT_LOGFILE 2>&1
+        test $RETVAL == 0 && success || failure
         ;;
     status)
         status $prog
@@ -521,5 +518,7 @@ case "$1" in
         ;;
     *)
         echo "Usage: ovirt-early {start}"
-        exit 2
+        RETVAL=2
 esac
+
+exit $RETVAL
