Reworked logging for standalone mode
Entire firstboot is logged to both console/logfile using tee.  Selected
sections of the code are set to only log stdout/stderr to logfile to prevent
data overload on console.  In these cases log() function is used to write
to the console.
TEE and log() must not be redefined in the scripts.

Signed-off-by: Perry Myers <pmyers@redhat.com>

diff --git a/scripts/ovirt-config-boot b/scripts/ovirt-config-boot
--- a/scripts/ovirt-config-boot
+++ b/scripts/ovirt-config-boot
@@ -22,19 +22,21 @@
 . /etc/init.d/functions
 . /etc/init.d/ovirt-functions
 
+trap '__st=$?; stop_log; exit $__st' 0
+trap 'exit $?' 1 2 13 15
 
 ovirt_boot_setup() {
     local disk=$1
     local live=$2
     local bootparams=$3
-    printf "installing oVirt Node image ... "
+    log "installing oVirt Node image."
     mount_boot
     # check that /boot mounted ok and find partition number for GRUB
     BOOT=$(mount|awk '$3 == "/boot" {print $1}')
     BOOT=$(( ${BOOT#$disk} - 1 ))
     rc=$?
     if [ $rc -ne 0 -o $BOOT -lt 0 ]; then
-      printf "boot partition not available\n"
+      log "boot partition not available."
       return $rc
     fi
     mount_liveos
@@ -54,7 +56,7 @@ ovirt_boot_setup() {
     && cp -p $live/$syslinux/vmlinuz0 /boot
     rc=$?
     if [ $rc -ne 0 ]; then
-      printf "image copy failed\n"
+      log "image copy failed."
       return $rc
     fi
     # append LVM support to the livecd initramfs
@@ -113,7 +115,7 @@ setup --prefix=/grub (hd0)
 EOF
     rc=$?
     if [ $rc -ne 0 ]; then
-        printf "boot loader install failed\n"
+        log "boot loader install failed."
         return $rc
     fi
     umount /liveos
@@ -121,14 +123,14 @@ EOF
 
     # caller decides when to reboot
     rm -rf $tmpdir
-    printf "done.\n"
+    log "done."
     # avoid reboot loops using Cobbler PXE only once
     # Cobbler XMLRPC post-install trigger (XXX is there cobbler SRV record?):
     # wget "http://192.168.50.2/cblr/svc/op/trig/mode/post/system/$(hostname)"
     #   -O /dev/null
 }
 
-
+start_log
 disk=$1
 live=$2
 bootparams=$3
@@ -150,13 +152,15 @@ parted $disk -s "print all" > /dev/null
 if [ 0 -eq $? ]; then
     ovirt_boot_setup "$disk" "$live" "$bootparams"
 else
-    printf "Please configure $disk before attempting to install the node image.\n"
-    printf "Use the option 'Disk Partitioning' from the main menu.\n"
+    log "Please configure $disk before attempting to install the node image."
+    log "Use the option 'Disk Partitioning' from the main menu."
     doreboot="no"
 fi
 
 if [ -z "$doreboot" -o "$doreboot" = "yes" ]; then
     disable_firstboot
     ovirt_store_firstboot_config
+    stop_log
     reboot
 fi
+stop_log
diff --git a/scripts/ovirt-config-networking b/scripts/ovirt-config-networking
--- a/scripts/ovirt-config-networking
+++ b/scripts/ovirt-config-networking
@@ -13,11 +13,10 @@ WORKDIR=$(mktemp -d) || exit 1
 
 # Remove $WORKDIR upon interrupt (and HUP, PIPE, TERM) and upon normal
 # termination, being careful not to change the exit status.
-trap '__st=$?; rm -rf "$WORKDIR"; exit $__st' 0
+trap '__st=$?; rm -rf "$WORKDIR"; stop_log; exit $__st' 0
 trap 'exit $?' 1 2 13 15
 
 CONFIG_FILE_ROOT="/files/etc/sysconfig/network-scripts/ifcfg"
-CONFIG_LOG_FILE="/var/log/ovirt-network-setup.log"
 
 function configure_interface
 {
@@ -220,7 +219,7 @@ else
     setup_menu
 
     while true; do
-        printf "\n\n oVirt Node Networking Configuration\n\n"
+        printf "\n\n oVirt Node Networking Configuration\n\n" >&2
 
         select NIC in $NICS
         do
@@ -234,13 +233,18 @@ else
     done
 fi
 
-{
-    printf "Configuring network.\n"
-    if ls "$WORKDIR"/augtool-* > /dev/null 2>&1 ; then
-        config="$WORKDIR"/config-augtool
-        cat "$WORKDIR"/augtool-* > $config \
-            && augtool $config  \
-            && service network restart
+start_log
+if ls "$WORKDIR"/augtool-* > /dev/null 2>&1 ; then
+    log "Configuring network"
+    config="$WORKDIR"/config-augtool
+    cat "$WORKDIR"/augtool-* > $config \
+        && augtool $config  \
+        && service network restart
+    if [ $? = 0 ]; then
+        log "Network configured successfully"
+    else
+        log "Error configuring network, see $OVIRT_LOGFILE"
     fi
-    ovirt_store_config /etc/sysconfig/network-scripts/ifcfg*
-} 2>&1 | tee $CONFIG_LOG_FILE
+fi
+ovirt_store_config /etc/sysconfig/network-scripts/ifcfg*
+stop_log
