updated unpersist prompts bz512539

diff --git a/scripts/ovirt-functions b/scripts/ovirt-functions
--- a/scripts/ovirt-functions
+++ b/scripts/ovirt-functions
@@ -508,8 +508,15 @@ remove_config() {
                     if [ -f /config$f ]; then
                         # refresh the file in rootfs if it was mounted over
                         cp -a /config$f $f
+                        if [ $? -ne 0 ]; then
+                            printf " Failed to unpersist %s\n" $f
+                        else
+                            printf " %s successully unpersisted\n" $f
+                        fi
                     fi
                 fi
+            else
+                printf " %s is not in persistent storage" $f
             fi
             # clean up the persistent store
             rm -f /config$f
