Encrypted swap support
(depends on Advance Storage Configuration patch)
This patch adds the option of requesting, at install time, that swap LVs be encrypted. The modifications include:

* Introduction of the ovirt_swap_encrypt install parameter
* Inclusion of all required packages
* Inclusion of required kernel modules
* Introduction of /etc/ovirt-crypttab to hold encrypted swap configuration (Couldn't use /etc/crypttab since it happens in rc.sysinit, before persistence is available
* Modification of ovirt-early so it automatically brings up encrypted swap, if available

It works as follows:
   swap_encrypt={Swap|Swap2},cypher1[:cypher2...][;{Swap|Swap2},...]
   the default cypher is set to aes-cbc-essiv:sha256

Signed-off-by: Ricardo Marin Matinata <matinata@br.ibm.com>

diff --git a/scripts/ovirt-functions b/scripts/ovirt-functions
--- a/scripts/ovirt-functions
+++ b/scripts/ovirt-functions
@@ -494,6 +494,50 @@ mount_data2() {
     fi
 }
 
+mount_crypt_swap() {
+    crypttab="/etc/ovirt-crypttab"
+    if [ ! -s "${crypttab}" ]; then
+        return 1
+    fi
+    rc=0
+
+    while read label dev mapp cyph; do
+        if [ -n ${label} -a -n ${dev} -a -n ${mapp} -a -n ${cyph} ]; then
+            if grep -q "${dev}" /proc/swaps; then
+                swapoff ${dev} >/dev/null 2>&1
+                rc=$?
+                [ ${rc} -ne 0 ] && {
+                    log "swapoff failed for Un-encrypted ${dev}";
+                    continue;
+                }
+            fi
+            if [ ! -b ${mapp} ]; then
+                /sbin/cryptsetup -d /dev/urandom -c ${cyph} create ${mapp} ${dev} > /dev/null 2>&1
+                rc=$?
+                [ ${rc} -ne 0 ] && {
+                    log "Creation of encrypted swap for ${dev} failed";
+                    continue;
+                }
+            fi
+            mkswap -L ${label} ${mapp} >/dev/null 2>&1
+            rc=$?
+            [ ${rc} -ne 0 ] && {
+                log "Creation of swap for ${mapp} failed";
+                continue;
+            }
+            swapon ${mapp} > /dev/null 2>&1
+            [ ${rc} -ne 0 ] && {
+                log "Activation of swap for ${mapp} failed";
+                continue;
+            }
+        else
+            continue
+        fi
+    done < ${cypttab}
+
+    return ${rc}
+}
+
 # augtool wrapper
 #   workaround for bind-mounted files
 #   see https://fedorahosted.org/augeas/ticket/32
