testable-node: Add igor support
test-able node is now capable of directly triggering a Igor run, if a
testplan is given.
Additionally testable-node can be pointed to a remote igor instance.

Note that igorc is not yet released.

Change-Id: I0fdc452ef964f0c655c688d69185f026691792cb
Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

diff --git a/tools/testable-node b/tools/testable-node
--- a/tools/testable-node
+++ b/tools/testable-node
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# testable-node Copyright (C) 2012 Red Hat, Inc.
+# testable-node Copyright (C) 2013 Red Hat, Inc.
 # Written by Fabian Deutsch <fabiand@fedoraproject.org>
 #
 # This program is free software; you can redistribute it and/or modify
@@ -22,17 +22,23 @@ isoname=""
 verbose=""
 reponame=""
 dry=false
+testplanname=""
+igorurl=""
 
+PLUGINPREFIX=ovirt-node-plugin-
 IGORPLUGIN=ovirt-node-plugin-igor-slave
 
 
 show_usage()
 {
-    echo "Usage: $0 [-vd] [-r <.repo-file>] -i <isoname>"
+    echo "Usage: $0 [-vdt] [-r <.repo-file>] [-a <url>] -i <isoname>"
     echo " -i    ISO file to be edited"
     echo " -v    Be verbose"
     echo " -r    Additional .repo file"
     echo " -d    Dry - don't execute edit-node"
+    echo " -t    Igor testplan to run on edited iso (if igorc is available)"
+    echo " -a    With -t: URL of the igor host"
+    echo "       (e.g. http://192.168.122.1:8080)"
     echo ""
     echo "$0 can be used to add the $IGORPLUGIN to a "
     echo "given ISO so it can be tested within an igor setup."
@@ -54,7 +60,7 @@ log()
 _parse_opts()
 {
     log "Parsing args: $@"
-    while getopts "h?vdi:r:" opt;
+    while getopts "h?vdi:r:t:a:" opt;
     do
         case "$opt" in
         h|\?)
@@ -69,10 +75,15 @@ _parse_opts()
             ;;
         d)  dry=true
             ;;
+        t)  testplanname=$OPTARG
+            ;;
+        a)  igorurl=$OPTARG
+            ;;
         esac
     done
 
     [[ -e "$isoname" ]] || die "<isoname> is missing or does not exist"
+    [[ "$testplanname" && -z "$igorurl" ]] && die "Igor URL is missing"
 
     shift $((OPTIND-1))
 
@@ -81,9 +92,11 @@ _parse_opts()
 
 main()
 {
-    TMPREPO=igor.repo
+    TMPREPO=$(mktemp -t --suffix .repo igor-repo-XXXX)
 
     _parse_opts "$@"
+
+    check_os_compatibility
 
     log "Generating temporary repository file: $TMPREPO"
     cmds="s/^\[/\[igor-/ ; /^mirrorlist/d ; s/^#base/base/ ; s/https:/http:/"
@@ -99,10 +112,42 @@ main()
     log "Dry: $dry"
     $dry || ./edit-node $ARGS
 
+    # Shall igorc be called?
+    [[ "$testplanname" ]] && test_with_igor
+
     # Keep temporary repo when in verbose mode
     [[ "$verbose" ]] || unlink $TMPREPO
 
     log "Done"
+}
+
+check_os_compatibility()
+{
+    [[ -e /etc/os-release ]] || die "No OS informations available"
+    . /etc/os-release
+    log "OS Release: $VERSION_ID"
+    ISORELEASE=$(echo $isoname | egrep -o "(fc|el)[0-9]+" | sed "s/fc\|el//")
+    log "ISO Release: $ISORELEASE"
+    [[ -z "$ISORELEASE" ]] && die "Failed to parse ISO release"
+    [[ $ISORELEASE -eq $VERSION_ID ]] || die "OS and ISO don't match."
+}
+
+test_with_igor()
+{
+    log "Running igor test on iso"
+    [[ -z "$(which igorc)" ]] && die "igorc is missing"
+
+    MAGICWORD=${IGORPLUGIN#$PLUGINPREFIX}
+    isoname_testable=$(ls -1 $(dirname $isoname) | grep $MAGICWORD | tail -n1)
+    isoname_testable=$(dirname $isoname)/$isoname_testable
+    log "Using testable ISO: $isoname_testable"
+
+    [[ -e "$isoname_testable" ]] || die "No testable ISO found."
+
+    igorc_cmdline="testplan_on_iso ${testplanname} ${isoname_testable} "
+    igorc_cmdline+="'local_boot_trigger=${igorurl}/testjob/{igor_cookie}'"
+    log "About to run igorc $igorc_cmdline"
+    $dry || igorc "$igorc_cmdline"
 }
 
 main "$@"
